project:
  type: website
  output-dir: docs
  render:
  - "*.qmd"

website:
  title: "Data Science in Oncology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Survival_Rates.qmd
      - Simple_classifier.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



